services:
  jupyter:
    image: oliverchenbz/jupyterlab_dev
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - .:/contrans2024
    networks:
      - dbnetwork
  postgres:
    image: postgres:latest   
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork
  mongo:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - dbnetwork

volumes:
  postgresdata:
  mongodata:

networks:
  dbnetwork:
